name: Release Helm Artifacts

on:
  workflow_dispatch:

env:
  HELM_CHART_VERSION: 1.0.2
  MATLAB_APP_VERSION: "R2024a"
  MATHWORKS_REGISTRY: "ghcr.io/esteinermw"

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package the chart
        run: helm package releases/${{ env.MATLAB_APP_VERSION }}/matlab-prodserver --version ${{ env.HELM_CHART_VERSION }} --app-version ${{ env.MATLAB_APP_VERSION }}

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_TOKEN }} | helm registry login ${{ env.MATHWORKS_REGISTRY }} --username esteinerMW --password-stdin

      - name: Deploy the chart
        run: helm push matlab-prodserver-k8s-${{ env.HELM_CHART_VERSION }}.tgz oci://${{ env.MATHWORKS_REGISTRY }}

